const nameDistricts = [
  'Ancón',
  'Ate',
  'Barranco',
  'Bellavista',
  'Breña',
  'Callao',
  'Carabayllo',
  'Carmen de La Legua-Reynoso',
  'Chaclacayo',
  'Chorrillos',
  'Cieneguilla',
  'Comas',
  'El Agustino',
  'Independencia',
  'Islas de San Lorenzo y el Frontón Islands Callao',
  'Jesús María',
  'La Molina',
  'La Perla',
  'La Punta',
  'La Victoria',
  'Lima',
  'Lince',
  'Los Olivos',
  'Lurigancho',
  'Lurín',
  'Magdalena del Mar',
  'Miraflores',
  'Pachacámac',
  'Pucusana',
  'Pueblo Libre',
  'Puente Piedra',
  'Punta Hermosa',
  'Punta Negra',
  'Rímac',
  'San Bartolo',
  'San Borja',
  'San Isidro',
  'San Juan de Lurigancho',
  'San Juan de Miraflores',
  'San Luis',
  'San Martín de Porres',
  'San Miguel',
  'Santa Anita',
  'Santa María del Mar',
  'Santa Rosa',
  'Santiago de Surco',
  'Surquillo',
  'Ventanilla',
  'Villa El Salvador',
  'Villa María del Triunfo',
];

const districts = nameDistricts.map((name, key) => ({ id: key, name: name }));

export default districts;